[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm install --legacy-peer-deps --no-fund --no-audit --ignore-engines"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve dist -s -l $PORT"
