[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm install --legacy-peer-deps --no-fund --no-audit --ignore-engines --ignore-scripts"]

[phases.build]
cmds = [
  "npm run build",
  "mkdir -p out/protocol",
  "cp -r dist/* out/protocol/",
  "cp dist/index.html out/index.html"
]

[start]
cmd = "npx serve out -s -l $PORT"
